apiVersion: serving.knative.dev/v1
kind: Service
metadata: 
  annotations: 
    run.googleapis.com/launch-stage: BETA
  name: my-php-sample
spec: 
  template: 
    metadata: 
      annotations: 
        run.googleapis.com/execution-environment: gen1 #or gen2
        run.googleapis.com/container-dependencies: '{"proxy":["pgadapter", "php"]}'
    spec: 
      containers: 
      - image: asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/my-app/my-nginx
        name: proxy
        ports: 
        - containerPort: 80
        volumeMounts: 
        - mountPath: /var/share
          name: share
      - image: gcr.io/cloud-spanner-pg-adapter/pgadapter
        name: pgadapter
        args:
        - "-p ${GOOGLE_CLOUD_PROJECT}"
        - "-i test-instance"
        - "-d game"
        - "-x"
        startupProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 10
          periodSeconds: 3
        resources: 
          limits: 
            cpu: "1"
            memory: 256Mi
        volumeMounts: 
        - mountPath: /var/share
          name: share
      - image: asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/my-app/my-php
        name: php
        resources: 
          limits: 
            cpu: "1"
            memory: 512Mi
        volumeMounts: 
        - mountPath: /var/share
          name: share
      volumes:
      - name: share
        emptyDir: 
          medium: Memory
          sizeLimit: 8Mi
